export interface TheorySection {
  heading: string;
  level: 1 | 2 | 3;
  content: string[];
}

export interface TheoryModule {
  num: number;
  title: string;
  pdfPages: string;
  tag: string;
  sections: TheorySection[];
}

export const THEORY_MODULES: Record<number, TheoryModule> = {
  // ══════════════════════════════════════════════════════════════
  // MÓDULO 1: TEORÍA INTUITIVA DE CONJUNTOS
  // ══════════════════════════════════════════════════════════════
  1: {
    num: 1,
    title: "Teoría Intuitiva de Conjuntos",
    pdfPages: "Págs. 1 – 3",
    tag: "Álgebra",
    sections: [
      {
        heading: "Nociones sobre Conjuntos",
        level: 1,
        content: [
          "Un **conjunto** es una colección de objetos, llamados **elementos** del conjunto.",
          "Un conjunto puede describirse:",
          "• **Por extensión:** haciendo una lista explícita de sus elementos, separados por comas y encerrados entre llaves, o",
          "• **Por comprensión:** dando la condición o condiciones que cumplen los elementos del conjunto.",
          "Ejemplo: $A = \\{x \\mid x \\text{ es una vocal de la palabra eucalipto}\\}$ es un conjunto descrito por comprensión, y su respectiva descripción por extensión es $A = \\{a, e, i, o, u\\}$.",
          "• Si un conjunto no tiene elementos se llama **conjunto vacío** y se denota por $\\emptyset$ ó $\\{\\}$.",
          "• Si un conjunto es vacío o su número de elementos es un número natural, se dice que el conjunto es **finito**. Si un conjunto no es finito, se dice que es **infinito**.",
          "Ejemplo: Sea $A = \\{x \\mid x \\text{ es una vocal cerrada en la palabra \"espejo\"}\\}$. Como no hay ninguna vocal cerrada en la palabra \"espejo\", entonces tenemos que $A = \\emptyset$.",
          "Ejemplo: Sea $A = \\{1, 2, 3\\}$. Luego, $A$ es finito, ya que posee $3$ elementos.",
          "Ejemplo: Sea $A = \\left\\{\\frac{1}{2}, \\frac{1}{3}, \\frac{1}{4}, \\frac{1}{5}, \\dots\\right\\}$. $A$ es infinito ya que no podemos asignar un número natural para su número de elementos.",
          "• Si $A$ es un conjunto, decimos que **$a$ pertenece a $A$** y escribimos $a \\in A$ si $a$ es un elemento de $A$. En caso contrario decimos que **$a$ no pertenece a $A$** y escribimos $a \\notin A$. En el último ejemplo, $\\frac{1}{2} \\in A$ y $5 \\notin A$.",
          "• Si $A$ y $B$ son conjuntos, decimos que **$A$ es subconjunto de $B$** y escribimos $A \\subseteq B$, si todo elemento de $A$ es también elemento de $B$. En caso de que haya al menos un elemento en el conjunto $A$ que no pertenece al conjunto $B$, decimos que $A$ no es subconjunto de $B$, y escribimos $A \\nsubseteq B$. Usando diagramas de Venn, podemos representar gráficamente los conjuntos.",
          "Ejemplo: Sean $A = \\{a, e, i, o, u\\}$ y $B = \\{x \\mid x \\text{ es una letra del abecedario}\\}$. Entonces $A \\subseteq B$, pero $B \\nsubseteq A$.",
        ],
      },
      {
        heading: "Propiedades e Igualdad de Conjuntos",
        level: 2,
        content: [
          "Teorema: Si $A, B$ y $C$ son conjuntos:",
          "• a) $\\emptyset \\subseteq A$.",
          "• b) $A \\subseteq A$.",
          "• c) Si $A \\subseteq B$ y $B \\subseteq C$, entonces $A \\subseteq C$.",
          "Definición: Dos conjuntos $A$ y $B$ son **iguales** si y sólo si $A \\subseteq B$ y $B \\subseteq A$. Es decir, $A = B$ si y sólo si todo elemento de $A$ está en $B$ y todo elemento de $B$ está en $A$.",
          "Ejemplo: Sean $A = \\{\\text{vocales de la palabra mundo}\\}$ y $B = \\{u, o\\}$, entonces $A = B$.",
          "Ejemplo: Sean $A = \\{1, 3, 7\\}$ y $B = \\{1, 3, 7, 1\\}$, entonces $A = B$.",
        ],
      },
      {
        heading: "Operaciones entre Conjuntos",
        level: 1,
        content: [
          "• **1. Unión:** Sean $A$ y $B$ dos conjuntos. Definimos la **unión** de $A$ y $B$, denotada $A \\cup B$, como el conjunto:",
          "$$A \\cup B = \\{x \\mid x \\in A \\text{ ó } x \\in B\\}$$",
          "Ejemplo: Sean $A = \\{1, 3, 5, 7, 9\\}$ y $B = \\{0, 3, 6, 9, 12\\}$. Entonces, $A \\cup B = \\{0, 1, 3, 5, 6, 7, 9, 12\\}$.",
          "• **2. Intersección:** Sean $A$ y $B$ dos conjuntos. Definimos la **intersección** de $A$ y $B$, denotada $A \\cap B$, como el conjunto:",
          "$$A \\cap B = \\{x \\mid x \\in A \\text{ y } x \\in B\\}$$",
          "Ejemplo: Sean $A = \\{1, 3, 5, 7, 9\\}$ y $B = \\{0, 3, 6, 9, 12\\}$. Entonces, $A \\cap B = \\{3, 9\\}$.",
          "• **3. Complemento:** Si $U$ es un conjunto universal y $A$ es un subconjunto de $U$, definimos el **complemento** de $A$, denotado $A'$ (ó $A^c$), como el conjunto:",
          "$$A' = \\{x \\in U \\mid x \\notin A\\}$$",
          "Ejemplo: Si $U = \\{a, b, c, d, e, f, g, h\\}$ y $A = \\{c, f, h\\}$, entonces $A' = \\{a, b, d, e, g\\}$.",
          "• **4. Diferencia:** Sean $A$ y $B$ dos conjuntos. Definimos la **diferencia** de $A$ y $B$, denotada $A - B$, como:",
          "$$A - B = \\{x \\mid x \\in A \\text{ y } x \\notin B\\}$$",
          "Ejemplo: Sean $A = \\{0, 1, 2, 3, 4, 5, 6, 7\\}$ y $B = \\{1, 4, 6, 7, 8, 9\\}$. Entonces $A - B = \\{0, 2, 3, 5\\}$.",
          "• **5. Diferencia Simétrica:** Sean $A$ y $B$ dos conjuntos. Definimos la **diferencia simétrica** de $A$ y $B$, denotada $A \\, \\Delta \\, B$, como:",
          "$$A \\, \\Delta \\, B = (A \\cup B) - (A \\cap B)$$",
          "o equivalentemente:",
          "$$A \\, \\Delta \\, B = (A - B) \\cup (B - A)$$",
          "Ejemplo: Consideremos los conjuntos $A = \\{0, 1, 2, 3, 4, 5, 6, 7\\}$ y $B = \\{1, 4, 6, 7, 8, 9\\}$. Por lo tanto, $A \\, \\Delta \\, B = \\{0, 2, 3, 5, 8, 9\\}$.",
        ],
      },
      {
        heading: "Propiedades de las Operaciones y Leyes de De Morgan",
        level: 2,
        content: [
          "Teorema: Sean $A, B$ y $C$ conjuntos. Para la unión y la intersección se satisfacen:",
          "• $A \\cup A = A \\quad \\text{y} \\quad A \\cap A = A$",
          "• $A \\cup \\emptyset = A \\quad \\text{y} \\quad A \\cap \\emptyset = \\emptyset$",
          "• $A \\subseteq (A \\cup B) \\quad \\text{y} \\quad (A \\cap B) \\subseteq A$",
          "• $B \\subseteq (A \\cup B) \\quad \\text{y} \\quad (A \\cap B) \\subseteq B$",
          "• $A \\cup B = B \\cup A \\quad \\text{y} \\quad A \\cap B = B \\cap A$",
          "• $A \\cup (B \\cup C) = (A \\cup B) \\cup C \\quad \\text{y} \\quad A \\cap (B \\cap C) = (A \\cap B) \\cap C$",
          "• $A \\cup (B \\cap C) = (A \\cup B) \\cap (A \\cup C)$",
          "• $A \\cap (B \\cup C) = (A \\cap B) \\cup (A \\cap C)$",
          "Propiedades del Complemento:",
          "• a) $(A')' = A$",
          "• b) $A \\cup A' = U$",
          "• c) $A \\cap A' = \\emptyset$",
          "• d) $(A \\cup B)' = A' \\cap B'$",
          "• e) $(A \\cap B)' = A' \\cup B'$",
          "Nota: Las dos últimas propiedades son conocidas como las **Leyes de De Morgan**.",
          "Propiedades de la Diferencia:",
          "• a) $A - B = A \\cap B'$",
          "• b) $A - B \\neq B - A$",
          "• c) $A - A = \\emptyset$",
          "• d) $A - \\emptyset = A$",
          "• e) $U - A = A'$",
        ],
      },
      {
        heading: "Sistemas Numéricos",
        level: 1,
        content: [
          "• **Números Naturales ($\\mathbb{N}$):** Son $1, 2, 3, 4, \\dots$. Representamos por $\\mathbb{N}$ al conjunto de todos los números naturales: $\\mathbb{N} = \\{1, 2, 3, 4, \\dots\\}$.",
          "• **Números Enteros ($\\mathbb{Z}$):** Están formados por los números naturales junto con los números negativos y el $0$: $\\mathbb{Z} = \\{\\dots, -3, -2, -1, 0, 1, 2, 3, \\dots\\}$. Algunas veces se acostumbra escribir $\\mathbb{Z}^+ = \\mathbb{N}$.",
          "• **Números Racionales ($\\mathbb{Q}$):** Se obtienen al formar cocientes de números enteros: $r \\in \\mathbb{Q} \\iff r = \\frac{p}{q}$, con $p, q \\in \\mathbb{Z}, q \\neq 0$. Números como $\\frac{3}{5}, -\\frac{7}{4}, 0 = \\frac{0}{1}, 2 = \\frac{2}{1}, 0.1 = \\frac{1}{10}$ son ejemplos de números racionales. ¡Recordar que no es posible dividir por cero, por tanto, expresiones como $\\frac{3}{0}$ ó $\\frac{0}{0}$ no están definidas!",
          "• **Números Irracionales ($\\mathbb{I}$):** Números que no pueden expresarse en la forma $\\frac{p}{q}$ con $p, q \\in \\mathbb{Z}, q \\neq 0$. Números como $\\sqrt{2}, \\sqrt{3}, \\sqrt{5}, e, \\pi$ pertenecen a $\\mathbb{I}$.",
          "• **Números Reales ($\\mathbb{R}$):** Consta de la unión de los racionales y los irracionales: $\\mathbb{R} = \\mathbb{Q} \\cup \\mathbb{I}$.",
          "• Todos los números reales tienen una **representación decimal**. Si el número es racional, su parte decimal es periódica: $\\frac{1}{2} = 0.5000\\dots = 0.5\\overline{0}$, $\\frac{1}{3} = 0.3333\\dots = 0.\\overline{3}$, $\\frac{157}{495} = 0.3171717\\dots = 0.3\\overline{17}$, $\\frac{9}{7} = 1.285714285714\\dots = 1.\\overline{285714}$. La barra significa que la sucesión de cifras se repite indefinidamente. Si el número es irracional, la representación decimal no es periódica: $\\sqrt{2} = 1.41421356\\dots$, $e = 2.71828182\\dots$. En la práctica se acostumbra aproximar un número irracional por medio de uno racional: $\\sqrt{2} \\approx 1.4142, e \\approx 2.71828, \\pi \\approx 3.1416$.",
          "• Dada la representación decimal periódica de un número $x$, podemos hallar una fracción equivalente multiplicando éste por potencias adecuadas de $10$, y luego restando para eliminar la parte periódica.",
          "Ejemplo: Sea $x = 5.4383838\\dots$. Para convertirlo en un cociente de dos enteros, multiplicamos por dos potencias adecuadas de $10$:",
          "$$1000x = 5438.3838\\dots$$",
          "$$-10x = -54.3838\\dots$$",
          "$$990x = 5384$$",
          "Por consiguiente, $x = \\frac{5384}{990} = \\frac{2692}{495}$.",
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // MÓDULO 2: PROPIEDADES DE LOS NÚMEROS REALES
  // ══════════════════════════════════════════════════════════════
  2: {
    num: 2,
    title: "Propiedades de los Números Reales",
    pdfPages: "Págs. 4 – 6",
    tag: "Álgebra",
    sections: [
      {
        heading: "Operaciones con los Números Reales",
        level: 1,
        content: [
          "En $\\mathbb{R}$ se definen dos operaciones: **suma o adición** y **producto o multiplicación**. Si $a \\in \\mathbb{R}$ y $b \\in \\mathbb{R}$, la suma $a + b$ y el producto $a \\cdot b$ (ó $a \\times b$ ó $ab$) son elementos de $\\mathbb{R}$ que cumplen las siguientes propiedades:",
          "• **Conmutativa:** $a + b = b + a \\quad \\text{y} \\quad ab = ba$.",
          "• **Asociativa:** $(a + b) + c = a + (b + c) \\quad \\text{y} \\quad (ab)c = a(bc)$.",
          "• **Distributiva del producto con respecto a la suma:** $a(b + c) = ab + ac$.",
          "Ejemplo: Probar que $(a + b)(a + b) = aa + 2ab + bb$.",
          "Solución: Usando la propiedad distributiva del producto con respecto a la suma, tenemos que:",
          "$$(a + b)(a + b) = (a + b)a + (a + b)b = aa + ab + ab + bb = aa + 2ab + bb$$",
          "Usando el hecho de que $\\forall a \\in \\mathbb{R}, a \\cdot a = a^2$, escribimos la igualdad anterior como: $$(a + b)^2 = a^2 + 2ab + b^2$$",
        ],
      },
      {
        heading: "Otras Propiedades y Leyes de Signos",
        level: 2,
        content: [
          "Entre los números reales, el $0$ y el $1$ juegan un papel importante en la suma y el producto, respectivamente:",
          "• $0 \\in \\mathbb{R}$, es tal que $\\forall a \\in \\mathbb{R}, a + 0 = a$. Al número $0$ se le llama el **elemento neutro para la suma**.",
          "• Si $a \\in \\mathbb{R}$, $\\exists (-a) \\in \\mathbb{R}$, tal que $a + (-a) = 0$. Al número $-a$ se le llama el **inverso aditivo de $a$**.",
          "• $1 \\in \\mathbb{R}$ es tal que $\\forall a \\in \\mathbb{R}, a \\cdot 1 = a$. A $1$ se le llama el **elemento neutro para el producto**.",
          "• Si $a \\in \\mathbb{R}, a \\neq 0$, $\\exists \\left(\\frac{1}{a}\\right) \\in \\mathbb{R}$, tal que $a \\cdot \\frac{1}{a} = 1$. Al número $\\frac{1}{a}$ se le llama el **inverso multiplicativo ó recíproco de $a$**, y también se denota por $a^{-1}$.",
          "• Si $a$ y $b$ son números reales, el número $a + (-b)$ se escribe también $a - b$ y se llama la **resta o diferencia de $a$ y $b$**.",
          "• Si $a$ y $b$ son números reales, con $b \\neq 0$, el número $a \\cdot \\frac{1}{b}$ se escribe también $\\frac{a}{b}$ y se llama el **cociente de $a$ y $b$**. A la expresión $\\frac{a}{b}$ se le llama **fracción**, $a$ se llama numerador y $b$ denominador de la fracción.",
          "Leyes de Signos: Con base en las definiciones y en las propiedades de la suma y la resta de números reales, se satisfacen:",
          "• 1. $(-1)a = -a$",
          "• 2. $-(-a) = a$",
          "• 3. $(-a)b = a(-b) = -ab$",
          "• 4. $(-a)(-b) = ab$",
          "• 5. $-(a + b) = -a - b \\quad$ (para más de dos términos: $-(a + b + c) = -a - b - c$)",
          "• 6. $-(a - b) = b - a \\quad$ (la propiedad nos dice que $a - b$ es el inverso aditivo de $b - a$)",
          "Ejemplo: Utilizando propiedades escriba las siguientes expresiones sin usar paréntesis:",
          "a) $-(-x + y) = -(-x) - y = x - y$.",
          "b) $-(x - y + z) = -x - (-y) - z = -x + y - z$.",
        ],
      },
      {
        heading: "Caracterización y Propiedades de Números Reales",
        level: 2,
        content: [
          "• **Número Par:** Un número $a$ es un número par si puede escribirse en la forma $a = 2k$, con $k \\in \\mathbb{Z}$. Ejemplos: $6 = 2(3)$ es par; $0 = 2(0)$ es par; $-8 = 2(-4)$ es par.",
          "• **Número Impar:** Un número $a$ es un número impar si puede escribirse en la forma $a = 2k + 1$, con $k \\in \\mathbb{Z}$. Ejemplos: $3 = 2(1) + 1$ es impar; $-7 = 2(-4) + 1$ es impar.",
          "• **Divisibilidad:** Dados $d \\in \\mathbb{Z}$ y $b \\in \\mathbb{Z}$, con $d \\neq 0$, decimos que **$d$ divide a $b$** ó que **$d$ es un divisor de $b$**, si existe $a \\in \\mathbb{Z}$ tal que $b = ad$. También se acostumbra decir que $d$ es un factor de $b$ y que $b$ es un múltiplo de $d$.",
          "• **Máximo Común Divisor (MCD):** Decimos que $d$ es el MCD de los enteros $a$ y $b$, con $a \\neq 0$ ó $b \\neq 0$, si $d$ es el mayor número entero positivo que los divide a ambos. Ejemplos: el MCD de $24$ y $30$ es $6$; el MCD de $7$ y $18$ es $1$; el MCD de $0$ y $12$ es $12$.",
          "• **Mínimo Común Múltiplo (MCM):** Decimos que $m$ es el MCM de los enteros $a$ y $b$, con $a \\neq 0$ y $b \\neq 0$, si $m$ es el menor número entero positivo que es múltiplo de ambos. Ejemplos: el MCM de $6$ y $10$ es $30$; el MCM de $15$ y $14$ es $210$.",
          "• **Primos Relativos:** Dos números enteros $a, b$ son primos relativos si el MCD de $a$ y $b$ es $1$. Ejemplo: $7$ y $18$ son primos relativos.",
          "• **Fracción Reducida:** Un número racional $\\frac{a}{b}$ está en forma reducida (simplificado) si $a$ y $b$ son primos relativos. $\\frac{7}{18}$ está en forma reducida; $\\frac{16}{12}$ se simplifica a $\\frac{4}{3}$. Todo número racional puede representarse en forma reducida: $\\frac{18}{8} = \\frac{9}{4}$.",
          "• **Número Primo:** Un entero positivo $p \\neq 1$ es un número primo si sus únicos divisores positivos son $1$ y $p$. Los números $2, 3, 5, 7, 11, 37, 523$ son números primos. Los números $6, 8, 9, 20$ no son primos. Los números primos forman un conjunto infinito.",
          "• **Número Compuesto:** Si $a \\in \\mathbb{Z}, a > 1$, y $a$ no es primo, decimos que $a$ es número compuesto.",
          "Teorema: **Teorema Fundamental de la Aritmética:** Todo número entero mayor que $1$ puede descomponerse en forma única como un producto de números ó factores primos.",
          "Nota: En la descomposición de un número, los números primos pueden repetirse y no importa el orden en el que aparecen. Cuando escribimos un número como producto de factores primos, decimos que hemos **factorizado** el número.",
          "Ejemplo: $2^2 \\times 17 \\times 43$ es la descomposición o factorización de $2924$, es decir, $2924 = 2^2 \\times 17 \\times 43$.",
        ],
      },
      {
        heading: "Operaciones con Fracciones",
        level: 1,
        content: [
          "Sean $a, b, c, d$ números enteros.",
          "• **1. Suma con igual denominador:**",
          "$$\\frac{a}{c} + \\frac{b}{c} = \\frac{a + b}{c}, \\quad \\text{con } c \\neq 0$$",
          "Ejemplo: $\\frac{15}{7} + \\frac{23}{7} = \\frac{38}{7}$.",
          "• **2. Suma con distinto denominador:** Hallamos el Mínimo Común Denominador (MCD / MCM) de los denominadores, ampliamos cada fracción multiplicando numerador y denominador por el factor correspondiente, y sumamos las fracciones:",
          "Ejemplo: Calcule $\\frac{3}{64} + \\frac{7}{48}$.",
          "Solución: Como $64 = 2^6$ y $48 = 2^4 \\cdot 3$, el MCD de $64$ y $48$ es $2^6 \\cdot 3 = 192$. Ampliando las fracciones:",
          "$$\\frac{3}{64} + \\frac{7}{48} = \\frac{3 \\cdot 3}{64 \\cdot 3} + \\frac{7 \\cdot 4}{48 \\cdot 4} = \\frac{9}{192} + \\frac{28}{192} = \\frac{37}{192}$$",
          "• **3. Producto de fracciones:**",
          "$$\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{ac}{bd}, \\quad \\text{con } b \\neq 0 \\text{ y } d \\neq 0$$",
          "Ejemplo: $\\frac{2}{5} \\cdot \\frac{4}{3} = \\frac{8}{15}$.",
          "• **4. Cociente de dos fracciones:**",
          "$$\\frac{a}{b} \\div \\frac{c}{d} = \\frac{a}{b} \\cdot \\frac{1}{\\frac{c}{d}} = \\frac{a}{b} \\cdot \\frac{d}{c} = \\frac{ad}{bc}, \\quad \\text{con } b \\neq 0, c \\neq 0, \\text{ y } d \\neq 0$$",
          "Ejemplo: $\\frac{2}{5} \\div \\frac{3}{7} = \\frac{2}{5} \\cdot \\frac{7}{3} = \\frac{14}{15}$.",
          "• **5. Propiedad fundamental de fracciones equivalentes:**",
          "Ejemplo: Pruebe que $\\frac{a}{b} = \\frac{c}{d} \\implies ad = bc$, con $b \\neq 0$ y $d \\neq 0$.",
          "Solución: Si $\\frac{a}{b} = \\frac{c}{d}$, entonces $\\frac{a}{b} - \\frac{c}{d} = 0$, luego $\\frac{ad - bc}{bd} = 0$, y así $ad - bc = 0$, entonces $ad = bc$. Luego $\\frac{a}{b} = \\frac{c}{d} \\implies ad = bc$.",
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // MÓDULO 3: RECTA NUMÉRICA, ORDEN E INTERVALOS
  // ══════════════════════════════════════════════════════════════
  3: {
    num: 3,
    title: "Recta Numérica, Orden e Intervalos",
    pdfPages: "Págs. 7 – 9",
    tag: "Álgebra",
    sections: [
      {
        heading: "Orden en los Números Reales",
        level: 1,
        content: [
          "Todo número real se puede representar gráficamente como un punto sobre una línea recta, la cual llamaremos **recta real** y, recíprocamente, todo punto sobre la recta real representa un número real. Es decir, existe una correspondencia biunívoca entre los elementos de $\\mathbb{R}$ y los puntos de la recta real. El punto $0$ sobre la recta real es el **origen**.",
          "• Los **números positivos** son los que están ubicados a la \"derecha\" de $0$ en la recta real.",
          "• Los **números negativos** son los que están ubicados a la \"izquierda\" de $0$.",
          "Definición: Sean $a, b \\in \\mathbb{R}$:",
          "• Decimos que **$a$ es mayor que $b$** y escribimos $a > b$, si $a - b$ es un número positivo.",
          "• Decimos que **$a$ es menor que $b$**, y escribimos $a < b$, si $a - b$ es un número negativo.",
          "• La expresión $a \\le b$ es equivalente a tener $a < b$ ó $a = b$, y se lee \"$a$ es menor que o igual a $b$\".",
          "• Similarmente, $a \\ge b \\iff a > b \\text{ ó } a = b$, y se lee \"$a$ es mayor que o igual a $b$\".",
          "• Intuitivamente decimos que los números reales están **ordenados**, ya que si $a$ y $b$ son números reales, siempre podemos determinar si $a > b$ ó $a < b$ ó $a = b$.",
          "Observaciones:",
          "• Claramente si $a > b$, entonces $b < a$.",
          "• Se acostumbra escribir $a < b < c$ como forma corta de la expresión $a < b$ y $b < c$.",
          "• Notemos que decir que un número real $a$ es positivo es equivalente a escribir $a > 0$. De la misma manera, decir que $b$ es negativo es equivalente a $b < 0$.",
          "• Geométricamente, si $a$ y $b$ son números reales, $a > b$ si $a$ está a la \"derecha\" de $b$ en la recta real. En este caso decimos también que $b$ es menor que $a$, y escribimos $b < a$.",
          "Ejemplo: $3 < 5$ pues $5 - 3 = 2 > 0$. $4 \\le 4$ ya que $4 = 4$. Si ubicamos estos números en la recta real vemos que $3$ está a la izquierda de $5$, o equivalentemente, $5$ está a la derecha de $3$.",
        ],
      },
      {
        heading: "Propiedades de Orden",
        level: 2,
        content: [
          "1. Si $a \\in \\mathbb{R}$, entonces $a^2 = a \\cdot a > 0$ y $a^2 = 0$ sólo si $a = 0$. Con base en esto podemos afirmar que $1 > 0$, ya que como $1 \\neq 0$, entonces $1 = 1^2 > 0$, luego $1 > 0$.",
          "2. Sean $a, b, c \\in \\mathbb{R}$:",
          "• Si $a \\le b$ y $b \\le c$, entonces $a \\le c$.",
          "• $a = b$ ó $a < b$ ó $b < a$.",
          "• $a \\le b$ si y sólo si $a + c \\le b + c$.",
          "• Si $a \\le b$ y $c > 0$, entonces $ac \\le bc$.",
          "• Si $a \\le b$ y $c < 0$, entonces $ac \\ge bc$.",
          "• Si $a > 0, b > 0$ y $a \\ge b$, entonces $\\frac{1}{a} \\le \\frac{1}{b}$.",
          "Ejemplos:",
          "• $3 < 8$ y $3(-3) > 8(-3)$ ya que $-3 < 0$.",
          "• De acuerdo a la última propiedad, $0 < 2 < 3$ implica que $\\frac{1}{3} < \\frac{1}{2}$, lo cual es cierto.",
          "Observaciones: Con base en las propiedades anteriores podemos demostrar que:",
          "• $a > 0 \\implies -a < 0$, es decir, si $a$ es un número positivo entonces $-a$ es un número negativo.",
          "• $a < 0 \\implies -a > 0$, o sea, si $a$ es un número negativo, entonces $-a$ es positivo.",
        ],
      },
      {
        heading: "Intervalos",
        level: 1,
        content: [
          "Un **intervalo** es un subconjunto de $\\mathbb{R}$ de ciertas características. Sean $a$ y $b \\in \\mathbb{R}$, con $a < b$:",
          "• **Intervalo Abierto:** El intervalo abierto entre $a$ y $b$, denotado por $(a, b)$, es el conjunto de los números reales mayores que $a$ y menores que $b$. Así, $c \\in (a, b)$ si $a < c$ y $c < b$, combinado como $a < c < b$. Claramente $a \\notin (a, b)$ y $b \\notin (a, b)$:",
          "$$(a, b) = \\{x \\in \\mathbb{R} \\mid a < x < b\\}$$",
          "• **Intervalo Cerrado:** Se denomina intervalo cerrado desde $a$ hasta $b$, y se denota por $[a, b]$, al conjunto de los números reales mayores o iguales que $a$ y menores o iguales que $b$. Incluye los extremos $a$ y $b$ y todos los números comprendidos entre ellos:",
          "$$[a, b] = \\{x \\in \\mathbb{R} \\mid a \\le x \\le b\\}$$",
          "Tabla de tipos de intervalos:",
          "• **$(a, b)$:** $\\{x \\in \\mathbb{R} \\mid a < x < b\\}$ (Abierto)",
          "• **$[a, b]$:** $\\{x \\in \\mathbb{R} \\mid a \\le x \\le b\\}$ (Cerrado)",
          "• **$[a, b)$:** $\\{x \\in \\mathbb{R} \\mid a \\le x < b\\}$ (Semiabierto a derecha)",
          "• **$(a, b]$:** $\\{x \\in \\mathbb{R} \\mid a < x \\le b\\}$ (Semiabierto a izquierda)",
          "• **$(a, \\infty)$:** $\\{x \\in \\mathbb{R} \\mid x > a\\}$",
          "• **$[a, \\infty)$:** $\\{x \\in \\mathbb{R} \\mid x \\ge a\\}$",
          "• **$(-\\infty, b)$:** $\\{x \\in \\mathbb{R} \\mid x < b\\}$",
          "• **$(-\\infty, b]$:** $\\{x \\in \\mathbb{R} \\mid x \\le b\\}$",
          "• **$(-\\infty, \\infty)$:** $\\mathbb{R}$",
          "Ejemplo: Expresar en términos de desigualdades los siguientes intervalos y representarlos gráficamente:",
          "a) $[-3, 8] = \\{x \\in \\mathbb{R} \\mid -3 \\le x \\le 8\\}$.",
          "b) $(5, 12] = \\{x \\in \\mathbb{R} \\mid 5 < x \\le 12\\}$.",
          "c) $(-\\infty, 2) = \\{x \\in \\mathbb{R} \\mid x < 2\\}$.",
        ],
      },
      {
        heading: "Operaciones con Intervalos",
        level: 2,
        content: [
          "Como los intervalos son conjuntos, podemos realizar entre ellos las operaciones ya definidas para conjuntos.",
          "Ejemplo: $[5, 9] \\cup (3, 6) = (3, 9]$, ya que:",
          "$$\\{x \\in \\mathbb{R} \\mid 5 \\le x \\le 9\\} \\cup \\{x \\in \\mathbb{R} \\mid 3 < x < 6\\} = \\{x \\in \\mathbb{R} \\mid 3 < x \\le 9\\}$$",
          "Ejemplo: $[5, 9] \\cap (3, 6) = [5, 6)$, ya que:",
          "$$\\{x \\in \\mathbb{R} \\mid 5 \\le x \\le 9\\} \\cap \\{x \\in \\mathbb{R} \\mid 3 < x < 6\\} = \\{x \\in \\mathbb{R} \\mid 5 \\le x < 6\\}$$",
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // MÓDULO 4: VALOR ABSOLUTO Y DISTANCIA
  // ══════════════════════════════════════════════════════════════
  4: {
    num: 4,
    title: "Valor Absoluto y Distancia",
    pdfPages: "Pág. 10",
    tag: "Álgebra",
    sections: [
      {
        heading: "Distancia y Valor Absoluto",
        level: 1,
        content: [
          "Si $a$ y $b$ son dos números reales, la **distancia entre $a$ y $b$**, denotada por $d(a, b)$, es la medida del segmento que los une en la recta real.",
          "• $d(a, b) \\ge 0$, y $d(a, b) = 0$ cuando $a = b$.",
          "• $d(a, b) = d(b, a)$.",
          "El **valor absoluto** de un número $a$, denotado por $|a|$, es la distancia desde $a$ hasta $0$, es decir, $|a| = d(a, 0)$.",
          "Ejemplo:",
          "• a) $|8| = 8$",
          "• b) $|-7| = -(-7) = 7$",
          "• c) $|0| = 0$",
          "Para cualquier número real $a$, $|a| \\ge 0$, ya que la distancia es siempre positiva o cero, entonces:",
          "$$|a| = \\begin{cases} a & \\text{si } a \\ge 0 \\\\ -a & \\text{si } a < 0 \\end{cases}$$",
          "Ejemplo:",
          "• $|3 - e| = 3 - e \\quad (\\text{ya que } e < 3 \\implies 3 - e > 0)$.",
          "• $|2 - \\pi| = -(2 - \\pi) = \\pi - 2 \\quad (\\text{ya que } 2 < \\pi \\implies 2 - \\pi < 0)$.",
        ],
      },
      {
        heading: "Propiedades del Valor Absoluto",
        level: 2,
        content: [
          "Si $a$ y $b$ son números reales:",
          "• 1. $|a| \\ge 0$",
          "• 2. $|a| = |-a|$",
          "• 3. $-|a| \\le a \\le |a|$",
          "• 4. $|ab| = |a||b|$",
          "• 5. $\\left|\\frac{a}{b}\\right| = \\frac{|a|}{|b|}$, con $b \\neq 0$",
          "• 6. $|a + b| \\le |a| + |b|$. La igualdad se cumple cuando $a$ y $b$ tienen el mismo signo.",
        ],
      },
      {
        heading: "Cálculo de Distancia con Valor Absoluto",
        level: 1,
        content: [
          "Podemos calcular la distancia entre $a$ y $b$ utilizando el valor absoluto:",
          "En la recta real, la distancia entre $-2$ y $3$ es $5$, y es la misma distancia entre $3$ y $-2$:",
          "$$d(-2, 3) = |-2 - 3| = |-5| = 5 = |3 - (-2)| = d(3, -2)$$",
          "En general, si $a$ y $b$ son números reales:",
          "• a) $|a - b| = |b - a|$, ya que $|a - b| = |-(b - a)| = |b - a|$, por propiedad 2.",
          "• b) $d(a, b) = |a - b|$.",
          "En efecto:",
          "• Si $a \\ge b$, la distancia entre $a$ y $b$ es $a - b$ y como $a - b \\ge 0$, entonces $|a - b| = a - b = d(a, b)$.",
          "• Si $a \\le b$, la distancia entre $a$ y $b$ es $b - a$, y como $b - a \\ge 0$, entonces $a - b \\le 0$ y $|a - b| = -(a - b) = b - a = d(a, b)$.",
          "Con base en lo anterior tenemos que $d(0, a) = |a|$, ya que $d(0, a) = |0 - a| = |-a| = |a|$.",
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // MÓDULO 5: POTENCIACIÓN Y RADICACIÓN
  // ══════════════════════════════════════════════════════════════
  5: {
    num: 5,
    title: "Potenciación y Radicación",
    pdfPages: "Págs. 11 – 14",
    tag: "Álgebra",
    sections: [
      {
        heading: "Exponentes Enteros",
        level: 1,
        content: [
          "Si $a, x \\in \\mathbb{R}$, una expresión de la forma $a^x$ se llama **expresión exponencial**, el número $a$ se llama **base**, y el número $x$ se conoce como **exponente**.",
          "• **a) Exponentes enteros positivos ó naturales:** Si $a \\in \\mathbb{R}$, el producto $a \\cdot a \\cdots a$ se denota por $a^n$, donde $n \\in \\mathbb{N}$ indica el número de veces que se repite el factor $a$, y se llama la $n$-ésima potencia de $a$:",
          "$$a^n = \\underbrace{a \\cdot a \\cdots a}_{n \\text{ factores}}$$",
          "Ejemplos:",
          "• $\\left(\\frac{1}{2}\\right)^4 = \\frac{1}{2} \\cdot \\frac{1}{2} \\cdot \\frac{1}{2} \\cdot \\frac{1}{2} = \\frac{1}{16}$",
          "• $(-5)^6 = (-5) \\cdot (-5) \\cdot (-5) \\cdot (-5) \\cdot (-5) \\cdot (-5) = 15625$",
          "• $-5^6 = -(5 \\cdot 5 \\cdot 5 \\cdot 5 \\cdot 5 \\cdot 5) = -15625$",
          "• $0^5 = 0 \\cdot 0 \\cdot 0 \\cdot 0 \\cdot 0 = 0$",
          "• **b) Exponente 0:** Si $a \\neq 0$ es un número real, definimos $a^0 = 1$. (Nota: La expresión $0^0$ no tiene sentido, ya que definimos $a^0$ para $a \\neq 0$).",
          "Ejemplos: $\\left(\\frac{3}{2}\\right)^0 = 1$, $(-5)^0 = 1$.",
          "• **c) Exponentes enteros negativos:** Si $a \\in \\mathbb{R}, a \\neq 0$ y $n$ es un entero positivo ($n > 0$), entonces $-n < 0$. Definimos: $$a^{-n} = \\frac{1}{a^n}$$",
          "Ejemplos: $3^{-2} = \\frac{1}{3^2} = \\frac{1}{9}$, $(-5)^{-1} = \\frac{1}{(-5)^1} = -\\frac{1}{5}$, $x^{-1} = \\frac{1}{x}$.",
        ],
      },
      {
        heading: "Propiedades de los Exponentes Enteros (Leyes de los Exponentes)",
        level: 2,
        content: [
          "Si $a, b \\in \\mathbb{R}$ y $m, n \\in \\mathbb{Z}$, entonces:",
          "• **1.** $a^m a^n = a^{m+n}$ (Ejemplo: $5^3 \\cdot 5^6 = 5^{3+6} = 5^9$)",
          "• **2.** $\\frac{a^m}{a^n} = a^{m-n}, \\quad a \\neq 0$ (Ejemplo: $\\frac{4^7}{4^2} = 4^{7-2} = 4^5$)",
          "• **3.** $(a^m)^n = a^{mn}$ (Ejemplo: $(7^6)^3 = 7^{6 \\cdot 3} = 7^{18}$)",
          "• **4.** $(ab)^n = a^n b^n$ (Ejemplo: $(5 \\cdot 8)^4 = 5^4 8^4$)",
          "• **5.** $\\left(\\frac{a}{b}\\right)^n = \\frac{a^n}{b^n}, \\quad b \\neq 0$ (Ejemplo: $\\left(\\frac{9}{4}\\right)^2 = \\frac{9^2}{4^2}$)",
          "• **6.** $\\left(\\frac{a}{b}\\right)^{-n} = \\left(\\frac{b}{a}\\right)^n, \\quad (a, b \\neq 0)$ (Ejemplo: $\\left(\\frac{5}{3}\\right)^{-2} = \\left(\\frac{3}{5}\\right)^2$)",
          "• **7.** $\\frac{a^{-n}}{b^{-m}} = \\frac{b^m}{a^n}, \\quad (a, b \\neq 0)$ (Ejemplo: $\\frac{4^{-3}}{7^{-5}} = \\frac{7^5}{4^3}$)",
          "Ejercicios Resueltos de Simplificación:",
          "• a) $(4a^4 b^3)^2 (5a^2 b^5) = (4^2 (a^4)^2 (b^3)^2)(5a^2 b^5) = (16a^8 b^6)(5a^2 b^5) = 80a^{10} b^{11}$.",
          "• b) $\\left(\\frac{3xy^2}{2x^{-1}z^2}\\right)^2 \\left(\\frac{x^2 z^2}{3y^2}\\right) = \\frac{9x^2 y^4}{4x^{-2} z^4} \\cdot \\frac{x^2 z^2}{3y^2} = \\frac{3x^6 y^2}{4z^2}$.",
          "• c) $\\left(\\frac{xy^{-2}z^{-3}}{x^2 y^3 z^{-4}}\\right)^{-3} = \\left(\\frac{x^2 y^3 z^{-4}}{xy^{-2}z^{-3}}\\right)^3 = (x y^5 z^{-1})^3 = \\frac{x^3 y^{15}}{z^3}$.",
        ],
      },
      {
        heading: "Notación Científica",
        level: 2,
        content: [
          "Un número $x$ está escrito en **notación científica** si está expresado en la forma: $$x = a \\times 10^n, \\quad \\text{donde } 1 \\le |a| < 10$$",
          "Ejemplos:",
          "• El número $325.32$ escrito en notación científica es $3.2532 \\times 10^2$.",
          "• $0.000354 = 3.54 \\times 10^{-4}$.",
          "• $-\\frac{2}{25} = -0.08 = -8 \\times 10^{-2}$.",
        ],
      },
      {
        heading: "Radicación y Exponentes Racionales",
        level: 1,
        content: [
          "• **I. Expresiones de la forma $a^{1/n}$ ($n \\in \\mathbb{N}$):**",
          "La expresión $a^{1/n}$ se escribe $\\sqrt[n]{a}$ y se llama **raíz $n$-ésima principal de $a$**. Para $n = 2$, $\\sqrt[2]{a}$ se escribe $\\sqrt{a}$ (raíz cuadrada principal).",
          "Definición: $\\sqrt[n]{a} = b$ significa que $b^n = a$.",
          "• Si $n$ es par: $\\sqrt[n]{a}$ sólo está definida para $a \\ge 0$ (y $b \\ge 0$).",
          "• Si $n$ es impar: $\\sqrt[n]{a}$ está definida para todo $a \\in \\mathbb{R}$.",
          "Ejemplos: $\\sqrt[4]{625} = 5$ (ya que $5^4 = 625$), $\\sqrt[3]{-27} = -3$ (ya que $(-3)^3 = -27$), $\\sqrt[4]{-81}$ no está definida en $\\mathbb{R}$ puesto que $4$ es par y $-81 < 0$.",
          "Importante: Si $a \\in \\mathbb{R}$, $\\sqrt{a^2} = |a|$. Ejemplo: $\\sqrt{3^2} = 3$, pero $\\sqrt{(-3)^2} = |-3| = 3 \\neq -3$.",
          "Propiedades de los Radicales (con $a, b$ positivos si $n$ es par):",
          "• 1. $\\sqrt[n]{ab} = \\sqrt[n]{a} \\sqrt[n]{b}$ (Ejemplo: $\\sqrt[3]{-27 \\cdot 64} = \\sqrt[3]{-27}\\sqrt[3]{64} = (-3)(4) = -12$)",
          "• 2. $\\sqrt[n]{\\frac{a}{b}} = \\frac{\\sqrt[n]{a}}{\\sqrt[n]{b}}, \\; b \\neq 0$ (Ejemplo: $\\sqrt{\\frac{4}{9}} = \\frac{\\sqrt{4}}{\\sqrt{9}} = \\frac{2}{3}$)",
          "• 3. $\\sqrt[m]{\\sqrt[n]{a}} = \\sqrt[mn]{a}$ (Ejemplo: $\\sqrt[3]{\\sqrt{729}} = \\sqrt[6]{729} = 3$)",
          "• 4. $\\sqrt[n]{c^n} = |c|$ si $n$ es par (Ejemplo: $\\sqrt[4]{3^4} = 3$ y $\\sqrt[4]{(-5)^4} = |-5| = 5$)",
          "• 5. $\\sqrt[n]{c^n} = c$ si $n$ es impar (Ejemplo: $\\sqrt[7]{(-2)^7} = -2$)",
          "• 6. $c\\sqrt[n]{b} + d\\sqrt[n]{b} = (c + d)\\sqrt[n]{b}$ (Ejemplo: $3\\sqrt[4]{5} + 6\\sqrt[4]{5} = 9\\sqrt[4]{5}$)",
          "Ejercicios de Simplificación de Radicales:",
          "• a) $\\sqrt{a^2 b^6} = \\sqrt{a^2}\\sqrt{b^6} = |a|\\sqrt{(b^3)^2} = |a||b^3|$.",
          "• b) $\\sqrt[3]{x^3 y^9} = \\sqrt[3]{x^3}\\sqrt[3]{(y^3)^3} = xy^3$.",
          "• c) $\\sqrt[4]{48} - \\sqrt[4]{3} = \\sqrt[4]{16 \\cdot 3} - \\sqrt[4]{3} = 2\\sqrt[4]{3} - \\sqrt[4]{3} = \\sqrt[4]{3}$.",
          "• **II. Expresiones de la forma $a^{m/n}$ ($m, n \\in \\mathbb{Z}, n > 0$):**",
          "$$a^{m/n} = (a^{1/n})^m = (\\sqrt[n]{a})^m = \\sqrt[n]{a^m}$$",
          "Ejemplos de Evaluación:",
          "• a) $\\left(\\frac{4}{9}\\right)^{-1/2} = \\left(\\frac{9}{4}\\right)^{1/2} = \\frac{\\sqrt{9}}{\\sqrt{4}} = \\frac{3}{2}$.",
          "• b) $\\left(-\\frac{27}{8}\\right)^{2/3} = \\frac{(\\sqrt[3]{-27})^2}{(\\sqrt[3]{8})^2} = \\frac{(-3)^2}{2^2} = \\frac{9}{4}$.",
          "Ejercicios de Simplificación con Exponentes Racionales:",
          "• a) $(2x^4 y^{-4/5})^3 (8y^2)^{2/3} = (8x^{12} y^{-12/5})((\\sqrt[3]{8})^2 y^{4/3}) = 32 x^{12} y^{4/3 - 12/5} = 32 x^{12} y^{-16/15} = \\frac{32x^{12}}{y^{16/15}}$.",
          "• b) $\\frac{(y^{10} z^{-5})^{1/5}}{(y^{-2} z^3)^{1/3}} = \\frac{y^2 z^{-1}}{y^{-2/3} z} = \\frac{y^2 y^{2/3}}{z \\cdot z} = \\frac{y^{8/3}}{z^2}$.",
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // MÓDULO 6: EXPRESIONES ALGEBRAICAS – POLINOMIOS
  // ══════════════════════════════════════════════════════════════
  6: {
    num: 6,
    title: "Expresiones Algebraicas – Polinomios",
    pdfPages: "Págs. 15 – 20",
    tag: "Álgebra",
    sections: [
      {
        heading: "Expresiones Algebraicas y Definición de Polinomio",
        level: 1,
        content: [
          "Una **expresión algebraica** es una combinación de constantes (números) y variables (elementos genéricos de un conjunto numérico, representados por letras), mediante suma, resta, multiplicación, división y potenciación con exponentes enteros o racionales.",
          "Ejemplos: $3x^2 + 4x - 5$, $\\frac{x + z}{y^2 + x}$, $\\frac{\\sqrt{y} - 4z}{z + y}$.",
          "Un **polinomio en la variable $x$** es una expresión algebraica de la forma:",
          "$$a_n x^n + a_{n-1} x^{n-1} + \\dots + a_1 x + a_0$$",
          "donde $a_0, a_1, \\dots, a_n$ son números reales, llamados **coeficientes del polinomio** y $n$ es un entero no negativo. Si $a_n \\neq 0$, se dice que el polinomio es de **grado $n$** (el mayor exponente de la variable que aparece en el polinomio).",
          "Ejemplo: $7x^5 - 3x^4 + 2x^2 + x + 1$ es un polinomio en la variable $x$ de grado $5$. El término en $x^3$ no se escribe porque su coeficiente es $0$.",
        ],
      },
      {
        heading: "Suma y Multiplicación de Polinomios",
        level: 2,
        content: [
          "• **Suma de polinomios:** Para sumar (o restar) polinomios, utilizamos las propiedades de la suma y el producto de números reales (agrupación y reducción de términos semejantes).",
          "Ejemplo: Sumar $3x^2 + 7x - 9$ con $-5x^3 - \\frac{1}{5}x^2 + x - 5$:",
          "$$(3x^2 + 7x - 9) + \\left(-5x^3 - \\frac{1}{5}x^2 + x - 5\\right) = -5x^3 + \\left(3 - \\frac{1}{5}\\right)x^2 + (7 + 1)x + (-9 - 5) = -5x^3 + \\frac{14}{5}x^2 + 8x - 14$$",
          "Ejemplo: De $3x^2 + x + 1$ restar $2x^2 - 3x - 5$:",
          "$$(3x^2 + x + 1) - (2x^2 - 3x - 5) = (3 - 2)x^2 + (1 + 3)x + (1 + 5) = x^2 + 4x + 6$$",
          "• **Producto de polinomios:** Para multiplicar polinomios usamos las propiedades distributivas y las leyes de los exponentes.",
          "Ejemplo: $(3x - 4)(x^2 + x) = 3x(x^2 + x) - 4(x^2 + x) = 3x^3 + 3x^2 - 4x^2 - 4x = 3x^3 - x^2 - 4x$.",
          "Ejemplo: $(\\sqrt{t} + 2)(5 - 2\\sqrt{t}) = 5\\sqrt{t} - 2(\\sqrt{t})^2 + 10 - 4\\sqrt{t} = \\sqrt{t} - 2t + 10$.",
        ],
      },
      {
        heading: "Productos Notables",
        level: 2,
        content: [
          "Sean $a$ y $b$ números reales o expresiones algebraicas:",
          "• 1. $(a + b)(a - b) = a^2 - b^2$",
          "• 2. $(a + b)^2 = a^2 + 2ab + b^2$",
          "• 3. $(a - b)^2 = a^2 - 2ab + b^2$",
          "• 4. $(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3$",
          "• 5. $(a - b)^3 = a^3 - 3a^2b + 3ab^2 - b^3$",
          "Interpretación geométrica:",
          "• $(a + b)^2$: Área de un cuadrado de lado $(a + b)$, que se descompone en cuatro rectángulos: un cuadrado de área $a^2$, un cuadrado de área $b^2$ y dos rectángulos de área $ab$.",
          "• $(a + b)^3$: Volumen de un cubo de lado $(a + b)$, descompuesto en $a^3$, tres prismas de volumen $a^2b$, tres prismas de volumen $ab^2$ y un cubo de volumen $b^3$.",
          "Ejemplos:",
          "• a) $\\left(c + \\frac{1}{c}\\right)^2 = c^2 + 2(c)\\left(\\frac{1}{c}\\right) + \\left(\\frac{1}{c}\\right)^2 = c^2 + 2 + \\frac{1}{c^2}, \\quad (c \\neq 0)$.",
          "• b) $\\left(\\sqrt{a} - \\frac{1}{b}\\right)\\left(\\sqrt{a} + \\frac{1}{b}\\right) = (\\sqrt{a})^2 - \\left(\\frac{1}{b}\\right)^2 = a - \\frac{1}{b^2}, \\quad (b \\neq 0)$.",
          "• c) $(1 - 2y)^3 = 1^3 - 3(1)^2(2y) + 3(1)(2y)^2 - (2y)^3 = 1 - 6y + 12y^2 - 8y^3$.",
        ],
      },
      {
        heading: "División de Polinomios y División Sintética",
        level: 1,
        content: [
          "Si $P(x)$ y $D(x)$ son polinomios tales que $\\deg(P) \\ge \\deg(D)$ y $D(x) \\neq 0$, existen polinomios únicos $Q(x)$ (cociente) y $R(x)$ (residuo) tales que:",
          "$$\\frac{P(x)}{D(x)} = Q(x) + \\frac{R(x)}{D(x)} \\iff P(x) = D(x) \\cdot Q(x) + R(x)$$",
          "con grado de $R(x)$ menor que el grado de $D(x)$.",
          "Ejemplo de División Larga: Dividir $5x^3 - 2x + 1$ entre $x + 1$:",
          "$$\\frac{5x^3 + 0x^2 - 2x + 1}{x + 1} = 5x^2 - 5x + 3 + \\frac{-2}{x + 1}$$",
          "donde $Q(x) = 5x^2 - 5x + 3$ es el cociente y $R(x) = -2$ es el residuo. Así: $5x^3 - 2x + 1 = (x + 1)(5x^2 - 5x + 3) - 2$.",
          "Ejemplo: Dividir $x^6 + x^4 + 2x^2 + 2$ entre $x^2 + 1$:",
          "$$\\frac{x^6 + x^4 + 2x^2 + 2}{x^2 + 1} = x^4 + 2 \\implies x^6 + x^4 + 2x^2 + 2 = (x^2 + 1)(x^4 + 2)$$ (en este caso el residuo es $0$, por lo que $x^2 + 1$ es un factor del dividendo).",
          "• **División Sintética:** Método rápido para dividir polinomios cuando el divisor es de la forma $x - c$ ($c \\in \\mathbb{R}$).",
          "Ejemplo: Dividir $x^4 - 3x^2 + 2x - 5$ entre $x + 2$ ($c = -2$):",
          "Coeficientes: $1, \\; 0, \\; -3, \\; 2, \\; -5$, con $c = -2$:",
          "• Bajamos $1$. Multiplicamos $1 \\times (-2) = -2$, sumamos $0 + (-2) = -2$.",
          "• Multiplicamos $-2 \\times (-2) = 4$, sumamos $-3 + 4 = 1$.",
          "• Multiplicamos $1 \\times (-2) = -2$, sumamos $2 + (-2) = 0$.",
          "• Multiplicamos $0 \\times (-2) = 0$, sumamos $-5 + 0 = -5$ (residuo).",
          "Cociente: $Q(x) = x^3 - 2x^2 + x$, Residuo: $R = -5$.",
          "Así: $x^4 - 3x^2 + 2x - 5 = (x + 2)(x^3 - 2x^2 + x) - 5$.",
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // MÓDULO 7: CEROS REALES DE POLINOMIOS
  // ══════════════════════════════════════════════════════════════
  7: {
    num: 7,
    title: "Ceros Reales de Polinomios",
    pdfPages: "Págs. 21 – 24",
    tag: "Álgebra",
    sections: [
      {
        heading: "Teorema del Residuo y Teorema del Factor",
        level: 1,
        content: [
          "• **Teorema del Residuo:** Si un polinomio $P(x)$ se divide entre $x - c$, entonces el residuo de la división es $P(c)$.",
          "Demostración: Como $x - c$ es un polinomio de grado 1, el residuo es una constante $d \\in \\mathbb{R}$: $P(x) = (x - c)Q(x) + d$. Evaluando en $c$: $P(c) = (c - c)Q(c) + d = d$.",
          "Ejemplo: Sin realizar la división, halle el residuo al dividir $-3x^2 + 2x - 1$ entre $x - 4$:",
          "Solución: $c = 4 \\implies P(4) = -3(4)^2 + 2(4) - 1 = -48 + 8 - 1 = -41$.",
          "• **Teorema del Factor:** Si $c \\in \\mathbb{R}$ y $P(x)$ es un polinomio, $x - c$ es un factor de $P(x)$ si y sólo si $P(c) = 0$.",
          "Ejemplo: Pruebe que $x + 3$ es un factor de $P(x) = x^3 + x^2 - 2x + 12$:",
          "Solución: $P(-3) = (-3)^3 + (-3)^2 - 2(-3) + 12 = -27 + 9 + 6 + 12 = 0$. Por tanto, $x - (-3) = x + 3$ es factor de $P(x)$.",
        ],
      },
      {
        heading: "Ceros Reales de Polinomios",
        level: 2,
        content: [
          "Los **ceros reales** de un polinomio $P(x) = a_n x^n + \\dots + a_1 x + a_0$ (o raíces de la ecuación polinómica $P(x) = 0$) son los valores $c \\in \\mathbb{R}$ tales que $P(c) = 0$.",
          "Observaciones: Si $P(x)$ es un polinomio en $x$ y $c \\in \\mathbb{R}$, los siguientes enunciados son equivalentes:",
          "• $c$ es un cero de $P(x)$.",
          "• $x = c$ es una raíz o una solución de la ecuación $P(x) = 0$.",
          "• $x - c$ es un factor de $P(x)$.",
          "• El punto $(c, 0)$ es un punto de intersección de la gráfica de $y = P(x)$ con el eje $x$.",
          "Ejemplo: Los ceros de $P(x) = x^2 - 5x + 6$ son $2$ y $3$, pues $P(2) = 0$ y $P(3) = 0$. Luego $P(x) = (x - 2)(x - 3)$. La parábola $y = x^2 - 5x + 6$ corta el eje $x$ en $(2, 0)$ y $(3, 0)$ con vértice en $(5/2, -1/4)$.",
          "• **Multiplicidad de un Cero:** Si $P(x) = (x - c)^m Q(x)$ con $Q(c) \\neq 0$ y $m \\ge 1$, decimos que $c$ es un cero de multiplicidad $m$.",
          "Ejemplo: Si $P(x) = (x - 4)(x + 2)^2 (x + 1)^4$, $4$ es un cero de multiplicidad $1$, $-2$ de multiplicidad $2$, y $-1$ de multiplicidad $4$.",
          "Ejemplo: Factorice $P(x) = 3x^3 - 2x - 20$:",
          "Solución: Evaluando en $2$, $P(2) = 3(2)^3 - 2(2) - 20 = 24 - 4 - 20 = 0$. Dividiendo por $x - 2$ mediante división sintética: $P(x) = (x - 2)(3x^2 + 6x + 10)$.",
          "Ejemplo: Hallar un polinomio $P(x)$ de grado 3 con ceros en $-1, 0, 3$:",
          "Solución: $P(x) = (x + 1)(x - 0)(x - 3) = x(x + 1)(x - 3) = x^3 - 2x^2 - 3x$.",
        ],
      },
      {
        heading: "Teorema de Ceros Racionales y Factorización",
        level: 1,
        content: [
          "Teorema: Si $P(x) = a_n x^n + a_{n-1}x^{n-1} + \\dots + a_1 x + a_0$ tiene coeficientes enteros, todo cero racional de $P$ tiene la forma $\\frac{p}{q}$, donde $p$ es factor (divisor) del término constante $a_0$, y $q$ es factor del coeficiente principal $a_n$.",
          "Ejemplo 1: Factorice completamente $P(x) = x^4 - 5x^3 - 5x^2 + 23x + 10$:",
          "• Divisores de $10$: $\\pm 1, \\pm 2, \\pm 5, \\pm 10$. Divisores de $1$: $\\pm 1$. Posibles ceros: $\\pm 1, \\pm 2, \\pm 5, \\pm 10$.",
          "• $P(1) = 24$, $P(-1) = -12$, $P(2) = 12$, $P(-2) = 0$.",
          "• Por división sintética entre $x + 2$: $P(x) = (x + 2)(x^3 - 7x^2 + 9x + 5)$.",
          "• Para $x^3 - 7x^2 + 9x + 5$, evaluamos en $5$: $5^3 - 7(5)^2 + 9(5) + 5 = 125 - 175 + 45 + 5 = 0$.",
          "• Por división sintética entre $x - 5$: $x^3 - 7x^2 + 9x + 5 = (x - 5)(x^2 - 2x - 1)$.",
          "• Factorizamos el cuadrático $x^2 - 2x - 1 = 0 \\implies x = \\frac{2 \\pm \\sqrt{4 + 4}}{2} = 1 \\pm \\sqrt{2}$.",
          "• Factorización completa: $$P(x) = (x + 2)(x - 5)[x - (1 + \\sqrt{2})][x - (1 - \\sqrt{2})]$$",
          "Ejemplo 2: Factorice completamente $P(x) = 3x^5 - 10x^4 - 6x^3 + 24x^2 + 11x - 6$:",
          "• $a_0 = -6$, $a_5 = 3$. Posibles ceros: $\\pm 1, \\pm \\frac{1}{3}, \\pm 2, \\pm \\frac{2}{3}, \\pm 3, \\pm 6$.",
          "• $P(-1) = 0 \\implies P(x) = (3x^4 - 13x^3 + 7x^2 + 17x - 6)(x + 1)$.",
          "• Evaluando de nuevo en $-1$: $3(-1)^4 - 13(-1)^3 + 7(-1)^2 + 17(-1) - 6 = 0 \\implies$ por división sintética obtenemos $(3x^3 - 16x^2 + 23x - 6)(x + 1)^2$.",
          "• Evaluando en $\\frac{1}{3}$: $3(1/3)^3 - 16(1/3)^2 + 23(1/3) - 6 = 0 \\implies 3x^3 - 16x^2 + 23x - 6 = (3x^2 - 15x + 18)\\left(x - \\frac{1}{3}\\right)$.",
          "• Finalmente, $3x^2 - 15x + 18 = 3(x^2 - 5x + 6) = 3(x - 3)(x - 2)$.",
          "• Factorización final: $$P(x) = 3(x - 3)(x - 2)\\left(x - \\frac{1}{3}\\right)(x + 1)^2$$ Ceros: $3, 2, \\frac{1}{3}$ (multiplicidad 1) y $-1$ (multiplicidad 2).",
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // MÓDULO 8: PRODUCTOS NOTABLES Y FACTORIZACIÓN
  // ══════════════════════════════════════════════════════════════
  8: {
    num: 8,
    title: "Productos Notables y Factorización",
    pdfPages: "Págs. 25 – 31",
    tag: "Álgebra",
    sections: [
      {
        heading: "Identidades de Productos Notables",
        level: 1,
        content: [
          "Sean $a$ y $b$ números reales o expresiones algebraicas. Tenemos las siguientes identidades:",
          "• 1. $(a + b)(a - b) = a^2 - b^2$",
          "• 2. $(a + b)^2 = a^2 + 2ab + b^2$",
          "• 3. $(a - b)^2 = a^2 - 2ab + b^2$",
          "• 4. $(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3$",
          "• 5. $(a - b)^3 = a^3 - 3a^2b + 3ab^2 - b^3$",
          "• 6. $(a + b)(a^2 - ab + b^2) = a^3 + b^3$",
          "• 7. $(a - b)(a^2 + ab + b^2) = a^3 - b^3$",
          "Interpretación geométrica:",
          "• $(a + b)^2$: Se visualiza como el área de un cuadrado de lado $a + b$, dividido en cuatro rectángulos: un cuadrado de área $a^2$, un cuadrado de área $b^2$ y dos rectángulos de área $ab$.",
          "• $(a + b)^3$: Se interpreta como el volumen de un cubo de lado $a + b$, descompuesto en un cubo de volumen $a^3$, tres prismas de volumen $a^2b$, tres prismas de volumen $ab^2$ y un cubo de volumen $b^3$.",
          "Ejemplos:",
          "• a) $\\left(b + \\frac{1}{b}\\right)^2 = b^2 + 2b\\left(\\frac{1}{b}\\right) + \\left(\\frac{1}{b}\\right)^2 = b^2 + 2 + \\frac{1}{b^2}, \\quad (b \\neq 0)$.",
          "• b) $\\left(\\sqrt{a} - \\frac{1}{c}\\right)\\left(\\sqrt{a} + \\frac{1}{c}\\right) = (\\sqrt{a})^2 - \\left(\\frac{1}{c}\\right)^2 = a - \\frac{1}{c^2}, \\quad (a \\ge 0, c \\neq 0)$.",
          "• c) $(1 - 2w)^3 = 1^3 - 3(1)^2(2w) + 3(1)(2w)^2 - (2w)^3 = 1 - 6w + 12w^2 - 8w^3$.",
        ],
      },
      {
        heading: "Factorización y Fórmulas Inversas",
        level: 1,
        content: [
          "Factorizar una expresión algebraica con respecto a $\\mathbb{R}$ es expresarla como un producto de expresiones más simples.",
          "Utilizando los productos notables podemos factorizar directamente:",
          "• **Diferencia de cuadrados:** $a^2 - b^2 = (a + b)(a - b)$",
          "• **Suma de cubos:** $a^3 + b^3 = (a + b)(a^2 - ab + b^2)$",
          "• **Diferencia de cubos:** $a^3 - b^3 = (a - b)(a^2 + ab + b^2)$",
          "• **Trinomio cuadrado perfecto:** $a^2 \\pm 2ab + b^2 = (a \\pm b)^2$",
          "• **Cubos perfectos:** $a^3 \\pm 3a^2b + 3ab^2 \\pm b^3 = (a \\pm b)^3$",
          "Ejemplos:",
          "• 1. $16w^2 - 9z^4 = (4w)^2 - (3z^2)^2 = (4w + 3z^2)(4w - 3z^2)$.",
          "• 2. $27b^3 + y^3 = (3b + y)[(3b)^2 - 3by + y^2] = (3b + y)(9b^2 - 3by + y^2)$.",
          "• 3. $64 - 125p^6 = (4 - 5p^2)(16 + 20p^2 + 25p^4) = (2 - \\sqrt{5}p)(2 + \\sqrt{5}p)(16 + 20p^2 + 25p^4)$.",
          "• 4. $x^4 + 10x^2 + 25 = (x^2 + 5)^2$.",
          "• 5. $81c^4 - d^4 = (9c^2 - d^2)(9c^2 + d^2) = (3c - d)(3c + d)(9c^2 + d^2)$.",
          "• 6. $X^{8m} - 16Y^{4n} = (X^{4m} - 4Y^{2n})(X^{4m} + 4Y^{2n}) = (X^{2m} - 2Y^n)(X^{2m} + 2Y^n)(X^{4m} + 4Y^{2n})$.",
        ],
      },
      {
        heading: "Casos Especiales de Factorización",
        level: 2,
        content: [
          "• **Caso 1. Factor Común:**",
          "  • a) $-2t^3 + 16t = -2t(t^2 - 8) = -2t(t + \\sqrt{8})(t - \\sqrt{8}) = -2t(t + 2\\sqrt{2})(t - 2\\sqrt{2})$.",
          "  • b) $-7a^4 k^2 + 14ak^3 + 21ak^4 = -7ak^2(a^3 - 2k - 3k^2)$.",
          "  • c) $(w + 2)^2 - 5(w + 2) = (w + 2)[(w + 2) - 5] = (w + 2)(w - 3)$.",
          "  • d) $m^4(m + 2)^3 + m^5(m + 2)^4 = m^4(m + 2)^3[1 + m(m + 2)] = m^4(m + 2)^3(m + 1)^2$.",
          "  • e) $ab^4 c^2 + a^3 bc^5 + a^2 b^2 c^2 = abc^2(b^3 + a^2 c^3 - ab)$.",
          "  • f) $xy^2 - b^2 x + xy + bx = x(y^2 - b^2 + y + b) = x[(y - b)(y + b) + (y + b)] = x(y + b)(y - b + 1)$.",
          "• **Caso 2. Trinomio $x^2 + bx + c$:** Se buscan $h, k$ tales que $h + k = b$ y $hk = c$:",
          "  • a) $x^2 - 6x + 5 = (x - 5)(x - 1)$.",
          "  • b) $(3x + 2)^2 + 4(3x + 2) - 12 = (3x + 2 + 6)(3x + 2 - 2) = (3x + 8)(3x)$.",
          "  • c) $b^3 - b^2 - 56b = b(b^2 - b - 56) = b(b - 8)(b + 7)$.",
          "  • d) $(a^2 - 2a)^2 - 2(a^2 - 2a) - 3 = (x - 3)(x + 1) = (a^2 - 2a - 3)(a^2 - 2a + 1) = (a - 3)(a + 1)(a - 1)^2$.",
          "• **Caso 3. Trinomio $ax^2 + bx + c$ ($a \\neq 1$):**",
          "  • a) $-6t^2 - 11t + 21 = -\\frac{1}{6}((6t)^2 + 11(6t) - 126) = -\\frac{1}{6}(6t + 18)(6t - 7) = (t + 3)(7 - 6t)$.",
          "  • b) $2c^2 + c - 1 = \\frac{1}{2}((2c)^2 + (2c) - 2) = \\frac{1}{2}(2c + 2)(2c - 1) = (c + 1)(2c - 1)$.",
          "• **Caso 4. Exponentes Racionales:** Sacar como factor común $x^q$ donde $q$ es el menor exponente:",
          "  • $x^{-5/2} + 2x^{-3/2} + x^{-1/2} = x^{-5/2}(1 + 2x + x^2) = x^{-5/2}(x + 1)^2$.",
          "• **Caso 5. Factorización por Agrupación:**",
          "  • a) $3x^3 - x^2 - 6x + 2 = x^2(3x - 1) - 2(3x - 1) = (3x - 1)(x^2 - 2) = (3x - 1)(x - \\sqrt{2})(x + \\sqrt{2})$.",
          "  • b) $a^3 + 27b^3 + a + 3b = (a^3 + 27b^3) + (a + 3b) = (a + 3b)(a^2 - 3ab + 9b^2) + (a + 3b) = (a + 3b)(a^2 - 3ab + 9b^2 + 1)$.",
          "  • c) $xy - vy + xz + wy + wz - vz = (xy - vy + wy) + (wz - vz + xz) = (x - v + w)y + (x - v + w)z = (x - v + w)(y + z)$.",
          "  • d) $\\frac{1}{2}x^{-1/2}(x + 5)^{1/2} - \\frac{1}{2}x^{1/2}(x + 5)^{-1/2} = \\frac{1}{2}x^{-1/2}(x + 5)^{-1/2}[(x + 5) - x] = \\frac{5}{2x^{1/2}(x + 5)^{1/2}}$.",
          "• **Caso 6. Diferencia de potencias $n$-ésimas:**",
          "  • $a^n - b^n = (a - b)(a^{n-1} + a^{n-2}b + a^{n-3}b^2 + \\dots + ab^{n-2} + b^{n-1})$.",
          "  • $x^5 - 1 = (x - 1)(x^4 + x^3 + x^2 + x + 1)$.",
          "  • $u^5 + 1 = u^5 - (-1)^5 = (u + 1)(u^4 - u^3 + u^2 - u + 1)$.",
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // MÓDULO 9: FACTORIAL Y TEOREMA DEL BINOMIO
  // ══════════════════════════════════════════════════════════════
  9: {
    num: 9,
    title: "Factorial y Teorema del Binomio",
    pdfPages: "Págs. 32 – 36",
    tag: "Álgebra",
    sections: [
      {
        heading: "Factorial y Combinaciones",
        level: 1,
        content: [
          "• **Definición de $n$ factorial:** Definimos $1! = 1, \\; 2! = 2 \\cdot 1 = 2$, y en general, si $n$ es cualquier número natural:",
          "$$n! = n \\cdot (n - 1) \\cdots 3 \\cdot 2 \\cdot 1$$",
          "Por conveniencia, se define $0! = 1$.",
          "• **Teorema de Permutaciones:** El número total de formas diferentes de ordenar $n$ objetos distintos (llamadas permutaciones) es $n!$.",
          "• **Combinaciones:** Si queremos formar todos los posibles subconjuntos de tamaño $r$ de un conjunto de $n$ elementos ($r \\le n$), sin importar el orden, diremos que estamos haciendo combinaciones. El número de subconjuntos de tamaño $r$ dado un conjunto de tamaño $n$ se denota $\\binom{n}{r}$:",
          "$$\\binom{n}{r} = \\frac{n!}{r! (n - r)!}$$",
          "La expresión $\\binom{n}{r}$ se lee \"$n$ tomados en grupos de $r$\" y se denomina **coeficiente binomial**.",
          "• **¿Cuándo aplicar combinaciones?** Se aplican cuando (1) no se permiten repeticiones, y (2) el orden es irrelevante.",
          "Ejemplos Resueltos:",
          "• **Ejemplo 1:** En un club con miembros $\\{A, B, C, D, E\\}$, se quieren formar comités de 3 miembros. Hay $\\binom{5}{3} = \\frac{5!}{3! 2!} = 10$ posibles comités: $\\{A,B,C\\}, \\{A,B,D\\}, \\{A,B,E\\}, \\{A,C,D\\}, \\{A,C,E\\}, \\{A,D,E\\}, \\{B,C,D\\}, \\{B,C,E\\}, \\{B,D,E\\}, \\{C,D,E\\}$.",
          "• **Ejemplo 2:** Elegir 4 videojuegos de 10 posibles: $\\binom{10}{4} = \\frac{10!}{4! (10 - 4)!} = 210$ maneras distintas.",
          "• **Ejemplo 3:** Elegir 12 asistentes entre 24 estudiantes: $\\binom{24}{12} = \\frac{24!}{12! 12!} = 2,704,156$ maneras diferentes.",
        ],
      },
      {
        heading: "El Teorema del Binomio",
        level: 1,
        content: [
          "Teorema: Si $n \\in \\mathbb{Z}^+$, entonces:",
          "$$(x + y)^n = \\binom{n}{0} x^n + \\binom{n}{1} x^{n-1} y + \\binom{n}{2} x^{n-2} y^2 + \\dots + \\binom{n}{n-1} x y^{n-1} + \\binom{n}{n} y^n$$",
          "o lo que es equivalente:",
          "$$(x + y)^n = x^n + n x^{n-1} y + \\frac{n(n - 1)}{2!} x^{n-2} y^2 + \\frac{n(n - 1)(n - 2)}{3!} x^{n-3} y^3 + \\dots + n x y^{n-1} + y^n$$",
          "• **Término general del desarrollo binomial:**",
          "  • El término que contiene $x^r$ en la expansión de $(x + y)^n$ es $\\binom{n}{n - r} x^r y^{n - r}$.",
          "  • El término que contiene $y^r$ en la expansión de $(x + y)^n$ es $\\binom{n}{r} x^{n - r} y^r$.",
          "Ejemplos:",
          "• **Ejemplo 1:** Desarrolle $(2a + b)^6$:",
          "$$(2a + b)^6 = (2a)^6 + 6(2a)^5 b + \\frac{6 \\times 5}{2!}(2a)^4 b^2 + \\frac{6 \\times 5 \\times 4}{3!}(2a)^3 b^3 + \\frac{6 \\times 5 \\times 4 \\times 3}{4!}(2a)^2 b^4 + 6(2a)b^5 + b^6$$",
          "$$= 64a^6 + 192a^5 b + 240a^4 b^2 + 160a^3 b^3 + 60a^2 b^4 + 12ab^5 + b^6$$",
          "• **Ejemplo 2:** Desarrolle $(2x - 5h)^4$:",
          "$$(2x - 5h)^4 = (2x)^4 + 4(2x)^3(-5h) + \\frac{4 \\times 3}{2!}(2x)^2(-5h)^2 + 4(2x)(-5h)^3 + (-5h)^4$$",
          "$$= 16x^4 - 160x^3 h + 600x^2 h^2 - 1000xh^3 + 625h^4$$",
          "• **Ejemplo 3:** Encuentre el coeficiente del término $x^{15}y^4$ en el desarrollo de $\\left(\\sqrt{x} + \\frac{y^2}{2}\\right)^{32}$:",
          "Tomando $r = 30$ (pues $(\\sqrt{x})^{30} = x^{15}$) y $n = 32$:",
          "$$\\binom{32}{2}(\\sqrt{x})^{30}\\left(\\frac{y^2}{2}\\right)^2 = 16 \\cdot 31 x^{15} \\frac{y^4}{4} = 124 x^{15} y^4 \\implies \\text{Coeficiente } = 124$$",
        ],
      },
      {
        heading: "El Triángulo de Pascal",
        level: 2,
        content: [
          "Los coeficientes binomiales de $(x + y)^n$ son los números de la $n$-ésima fila del Triángulo de Pascal:",
          "• $n = 0$: $1$",
          "• $n = 1$: $1 \\quad 1$",
          "• $n = 2$: $1 \\quad 2 \\quad 1 \\implies (x + y)^2 = x^2 + 2xy + y^2$",
          "• $n = 3$: $1 \\quad 3 \\quad 3 \\quad 1 \\implies (x + y)^3 = x^3 + 3x^2 y + 3xy^2 + y^3$",
          "• $n = 4$: $1 \\quad 4 \\quad 6 \\quad 4 \\quad 1 \\implies (x + y)^4 = x^4 + 4x^3 y + 6x^2 y^2 + 4xy^3 + y^4$",
          "• $n = 5$: $1 \\quad 5 \\quad 10 \\quad 10 \\quad 5 \\quad 1$",
          "• $n = 6$: $1 \\quad 6 \\quad 15 \\quad 20 \\quad 15 \\quad 6 \\quad 1 \\implies (x + y)^6 = x^6 + 6x^5 y + 15x^4 y^2 + 20x^3 y^3 + 15x^2 y^4 + 6xy^5 + y^6$",
          "Nota: El Triángulo de Pascal es más sencillo de aplicar cuando la potencia $n$ es relativamente pequeña, mientras que la fórmula del binomio es preferible para potencias grandes.",
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // MÓDULO 10: EXPRESIONES FRACCIONARIAS, FRACCIONES COMPUESTAS Y RACIONALIZACIÓN
  // ══════════════════════════════════════════════════════════════
  10: {
    num: 10,
    title: "Expresiones Fraccionarias, Fracciones Compuestas y Racionalización",
    pdfPages: "Págs. 37 – 41",
    tag: "Álgebra",
    sections: [
      {
        heading: "Expresiones Fraccionarias y Simplificación",
        level: 1,
        content: [
          "Se llama **expresión fraccionaria** o fracción al cociente de dos expresiones algebraicas. Ejemplos: $\\frac{4z^2}{z-1}, \\; \\frac{\\sqrt{y}-2}{y^3+5}, \\; \\frac{3x+1}{2x^{3/4}}$.",
          "Si en una expresión fraccionaria el numerador y el denominador son polinomios, la expresión se llama **expresión racional**. Ejemplos: $\\frac{5x^2}{x+2}, \\; \\frac{7x^3+2x^2-x+1}{4x^4+2x^2+1}$.",
          "• **1. Simplificación:** Factorizamos el numerador y el denominador, y luego aplicamos la propiedad $\\frac{AC}{BC} = \\frac{A}{B}$, cuando sea posible.",
          "Ejemplos:",
          "• a) $\\frac{x^2 - x - 2}{x^2 - 1} = \\frac{(x - 2)(x + 1)}{(x - 1)(x + 1)} = \\frac{x - 2}{x - 1}$.",
          "• b) $\\frac{1 - x^2}{x^3 - 1} = \\frac{(1 - x)(1 + x)}{(x - 1)(x^2 + x + 1)} = \\frac{-(x - 1)(1 + x)}{(x - 1)(x^2 + x + 1)} = -\\frac{1 + x}{x^2 + x + 1}$.",
        ],
      },
      {
        heading: "Operaciones con Fracciones Algebraicas",
        level: 2,
        content: [
          "• **Suma y Resta con MCM de denominadores:**",
          "  • a) $\\frac{1}{x^2} + \\frac{1}{x^2 + x} = \\frac{1}{x^2} + \\frac{1}{x(x + 1)} = \\frac{x + 1 + x}{x^2(x + 1)} = \\frac{2x + 1}{x^2(x + 1)}$.",
          "  • b) $\\frac{2}{x + 3} - \\frac{1}{x^2 + 7x + 12} = \\frac{2}{x + 3} - \\frac{1}{(x + 3)(x + 4)} = \\frac{2(x + 4) - 1}{(x + 3)(x + 4)} = \\frac{2x + 7}{(x + 3)(x + 4)}$.",
          "• **Multiplicación y División:**",
          "  • a) $\\frac{x^2 - x - 12}{x^2 - 9} \\cdot \\frac{3 + x}{4 - x} = \\frac{(x - 4)(x + 3)}{(x - 3)(x + 3)} \\cdot \\frac{x + 3}{-(x - 4)} = -\\frac{x + 3}{x - 3}$.",
          "  • b) $\\frac{4y^2 - 9}{2y^2 + 9y - 18} \\div \\frac{2y^2 + y - 3}{y^2 + 5y - 6} = \\frac{(2y - 3)(2y + 3)}{(2y - 3)(y + 6)} \\cdot \\frac{(y + 6)(y - 1)}{(2y + 3)(y - 1)} = 1$.",
          "  • c) $\\frac{\\frac{2x^2 - 3x - 2}{x^2 - 1}}{\\frac{2x^2 + 5x + 2}{x^2 + x - 2}} = \\frac{(2x + 1)(x - 2)(x + 2)(x - 1)}{(x^2 - 1)(2x^2 + 5x + 2)} = \\frac{(2x + 1)(x - 2)(x + 2)(x - 1)}{(x - 1)(x + 1)(2x + 1)(x + 2)} = \\frac{x - 2}{x + 1}$.",
        ],
      },
      {
        heading: "Fracciones Compuestas",
        level: 2,
        content: [
          "Si en una fracción, el numerador o el denominador son también fracciones, la expresión se llama **fracción compuesta**.",
          "Ejemplos de Simplificación:",
          "• a) $\\frac{\\frac{a-b}{a} - \\frac{a+b}{b}}{\\frac{a-b}{b} + \\frac{a+b}{a}} = \\frac{\\frac{b(a-b)-a(a+b)}{ab}}{\\frac{a(a-b)+b(a+b)}{ab}} = \\frac{ab-b^2-a^2-ab}{a^2-ab+ab+b^2} = \\frac{-(b^2+a^2)}{a^2+b^2} = -1$.",
          "• b) $\\frac{x^{-1} + y^{-1}}{(x + y)^{-1}} = \\frac{\\frac{1}{x} + \\frac{1}{y}}{\\frac{1}{x+y}} = \\frac{\\frac{y+x}{xy}}{\\frac{1}{x+y}} = \\frac{x+y}{xy} \\cdot \\frac{x+y}{1} = \\frac{(x+y)^2}{xy}$.",
          "• c) $\\frac{(1 - x^2)^{1/2} + x^2(1 - x^2)^{-1/2}}{1 - x^2} = \\frac{(1-x^2)^{-1/2}[(1-x^2)+x^2]}{1-x^2} = \\frac{(1-x^2)^{-1/2}}{1-x^2} = \\frac{1}{(1-x^2)^{3/2}}$.",
        ],
      },
      {
        heading: "Racionalización de Denominadores y Numeradores",
        level: 1,
        content: [
          "Dada una expresión fraccionaria con radicales en el denominador, **racionalizar el denominador** consiste en multiplicarla y dividirla por un factor adecuado para eliminar los radicales:",
          "• **1. Denominador $\\sqrt{a}$:** $\\frac{1}{\\sqrt{a}} = \\frac{1}{\\sqrt{a}} \\cdot \\frac{\\sqrt{a}}{\\sqrt{a}} = \\frac{\\sqrt{a}}{a}$. (Ejemplo: $\\frac{1}{\\sqrt{10}} = \\frac{\\sqrt{10}}{10}$).",
          "• **2. Denominador $\\sqrt[n]{a^m}$ ($m < n, a > 0$):** $\\frac{1}{\\sqrt[n]{a^m}} = \\frac{1}{\\sqrt[n]{a^m}} \\cdot \\frac{\\sqrt[n]{a^{n-m}}}{\\sqrt[n]{a^{n-m}}} = \\frac{\\sqrt[n]{a^{n-m}}}{a}$. (Ejemplo: $\\frac{2}{\\sqrt[3]{x}} = \\frac{2\\sqrt[3]{x^2}}{x}$).",
          "• **3. Denominador $a + b\\sqrt{c}$ (Multiplicar por conjugado $a - b\\sqrt{c}$):**",
          "$$\\frac{1}{a + b\\sqrt{c}} = \\frac{1}{a + b\\sqrt{c}} \\cdot \\frac{a - b\\sqrt{c}}{a - b\\sqrt{c}} = \\frac{a - b\\sqrt{c}}{a^2 - b^2 c}$$",
          "Ejemplo: $\\frac{2}{3 - \\sqrt{5}} = \\frac{2(3 + \\sqrt{5})}{9 - 5} = \\frac{3 + \\sqrt{5}}{2}$.",
          "Ejemplo: $\\frac{2(x - y)}{\\sqrt{x} - \\sqrt{y}} = \\frac{2(x - y)(\\sqrt{x} + \\sqrt{y})}{x - y} = 2(\\sqrt{x} + \\sqrt{y})$.",
          "• **4. Denominador $\\sqrt[3]{a} - \\sqrt[3]{b}$ (Multiplicar por $\\sqrt[3]{a^2} + \\sqrt[3]{ab} + \\sqrt[3]{b^2}$):**",
          "$$\\frac{1}{\\sqrt[3]{a} - \\sqrt[3]{b}} = \\frac{\\sqrt[3]{a^2} + \\sqrt[3]{ab} + \\sqrt[3]{b^2}}{a - b}$$",
          "Ejemplo: $\\frac{b}{\\sqrt{5} + \\sqrt{b}} = \\frac{b(\\sqrt{5} - \\sqrt{b})}{5 - b}$.",
          "Ejemplo: $\\frac{1}{\\sqrt{m} - \\sqrt[4]{n}} = \\frac{(\\sqrt{m} + \\sqrt[4]{n})(m + \\sqrt{n})}{m^2 - n}$.",
          "• **5. Racionalización del Numerador:**",
          "Ejemplo: $\\frac{\\sqrt{x} - \\sqrt{x+h}}{h\\sqrt{x}\\sqrt{x+h}} = \\frac{-h}{h\\sqrt{x}\\sqrt{x+h}(\\sqrt{x}+\\sqrt{x+h})} = \\frac{-1}{\\sqrt{x}\\sqrt{x+h}(\\sqrt{x}+\\sqrt{x+h})}$.",
          "Ejemplo: $\\frac{\\sqrt[3]{x} + \\sqrt[3]{2}}{x + 2} = \\frac{x + 2}{(x + 2)(\\sqrt[3]{x^2} - \\sqrt[3]{2x} + \\sqrt[3]{4})} = \\frac{1}{\\sqrt[3]{x^2} - \\sqrt[3]{2x} + \\sqrt[3]{4}}$.",
          "• **6. Errores Algebraicos Frecuentes (¡Cuidado!):**",
          "• $(a + b)^2 \\neq a^2 + b^2$",
          "• $\\sqrt{a + b} \\neq \\sqrt{a} + \\sqrt{b}$",
          "• $\\sqrt{a^2 + b^2} \\neq a + b$",
          "• $\\frac{1}{a} + \\frac{1}{b} \\neq \\frac{1}{a + b}$",
          "• $\\frac{a + b}{a} \\neq b$",
          "• $(a + b)^{-1} \\neq a^{-1} + b^{-1}$",
        ],
      },
    ],
  },
};

